version: 2

jobs:
  build:
    docker:
      - image: jeremigendron/rustbn_js
    steps:
      - checkout
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt
            git diff --exit-code
      - run:
          name: Cargo build
          command: cargo build --release --target asmjs-unknown-emscripten
      - run:
          name: Make All
          command: make
